# Generated by Django 4.2.23 on 2025-08-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbero',
            name='calendar_id',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
