# Generated by Django 5.2.4 on 2026-04-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_barbero_calendar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
