# Generated by Django 5.2.4 on 2026-04-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_cita_google_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbero',
            name='dia_descanso',
            field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], default=6),
        ),
    ]
