# Generated by Django 5.2.4 on 2026-04-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_barbero_dia_descanso'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='last_sync',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
