# Generated by Django 5.2.4 on 2026-04-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_cita_last_sync_alter_cita_google_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbero',
            name='imagen',
            field=models.CharField(help_text='Ruta estática. Ej: Barberia/Imagenes/Pimpon.jpeg', max_length=255),
        ),
    ]
